### ISSUE TITLE
convertCurrentWorkspacetoDemo doesn't overwrite an already existent workspace

### ISSUE THREAD

**Issue by juanludlf** [isa-group/ideas-studio#1]
We should add a new parameter to the command ("-f")  to force the overwrite. If this parameter is not present , and demo workspace  already exists, it should give an error message and prevent the overwriting

**Comment by antgamdia** [comment]
Verify compatibility with new demo management

**Comment by feserafim** [comment]
Nowadays, if you overwrite a demo workspace it might broke user demo version. This issue should be covered in the future.
Closing this issue.
