### ISSUE TITLE
Incorrect demo path when publishing

### ISSUE THREAD

**Issue by antgamdia** [isa-group/ideas-studio#110]
Image:

![image](https://cloud.githubusercontent.com/assets/11535726/12914759/9d68c156-cf26-11e5-8baa-01eddec88a90.png)

**Comment by feserafim** [comment]
There are a couple of commentaries related to this issue in #115 PR

**Comment by danyaljim** [comment]
I found some problems accessing demos after demo generation, 
workspace doesn't load correctly.
