### ISSUE TITLE
(string, required) to all help commands in gcli

### ISSUE THREAD

**Issue by feserafim** [isa-group/ideas-studio#12]
_From @feserafim on October 20, 2015 11:33_

When you execute `help` command in `gcli` all parameters marked `(string, required)`, although there are some ones  which are optionals.

_Copied from original issue: isa-group/ideas-studio-deprecated#12_

**Comment by antgamdia** [comment]
Estimation task effort

**Comment by antgamdia** [comment]
In commands.js you can add "defaultValue" attribute to make a command be optional.
