### ISSUE TITLE
Unable to login with Google in localhost

### ISSUE THREAD

**Issue by feserafim** [isa-group/ideas-studio#124]
This is what you get when you try to sing up using a Google account in localhost.

> ![captura de pantalla 2016-02-17 a las 17 35 55](https://cloud.githubusercontent.com/assets/2706008/13116650/fa9cdc5a-d59c-11e5-8c86-5ed8388639dd.png)

**Comment by feserafim** [comment]
@juanlu91 do you have any idea?

**Comment by juanludlf** [comment]
It's working properly to me. Can you confirm this bug with other team members?
![](https://i.gyazo.com/8f6bba98ce486d424122029a50827823.png)

**Comment by feserafim** [comment]
I've tried with my account and it works, but it won't work with IDEAS Google account. That's weird.

**Comment by danyaljim** [comment]
It also works with my google account.

**Comment by feserafim** [comment]
Yeah, but it won't work if you use IDEAS Google account :-(

**Comment by danyaljim** [comment]
I've tried and it's also working for IDEAS Google account. 
<img width="569" alt="captura de pantalla 2016-02-18 a las 10 24 48" src="https://cloud.githubusercontent.com/assets/798285/13139753/5f1a252a-d62e-11e5-8e33-994b38aa2ec3.png">
<img width="625" alt="captura de pantalla 2016-02-18 a las 10 24 58" src="https://cloud.githubusercontent.com/assets/798285/13139757/63209686-d62e-11e5-9e4c-3b6e716bb912.png">
<img width="584" alt="captura de pantalla 2016-02-18 a las 10 21 18" src="https://cloud.githubusercontent.com/assets/798285/13139760/685a9afc-d62e-11e5-8b7a-347563c647b4.png">

**Comment by feserafim** [comment]
I'm relieved it works for you. Thanks for testing it! :+1: 
I will try again later. Maybe there is a cache problem with my browser.

**Comment by antgamdia** [comment]
I was trying to reproduce it in my computer. The problems seems to be that, when a new user sign up, the system try to create a SampleDemoWorkspace. This is OK (remember to create DemoMaster in your ideas-repo). Nevertheless, it tries to create a new record in 'workspace' table in database. The column `owner_id` is marked as not-nullable, so there is an hibernate error that make imossible to a new user to access.

**Comment by feserafim** [comment]
I've just implemented a quick solution for it in 1024f1f3c73ee5d89370897f9739015540f7d663
For now, `SampleWorkspace` won't be created in database for a new user register.

I needed to implement this quick solution to be able to close #119.
