### ISSUE TITLE
Delete a workspace always ask for workspace demo delete

### ISSUE THREAD

**Issue by feserafim** [isa-group/ideas-studio#134]
You always get asked for demo delete although you don't have any demo.
Here a screenshot:

![captura de pantalla 2016-03-07 a las 21 01 12](https://cloud.githubusercontent.com/assets/2706008/13581565/d5ecf1fa-e4a7-11e5-9c43-ff7c23221b5d.png)

Also if you proceed, you get redirect to workspace manager page. On the other hand, if you press close, you won't be redirect anywhere although you've already deleted the workspace in the previous modal.

**Comment by antgamdia** [comment]
Now workspace deletion has been disabled (by deactivating "advancedMode" in studio-configuration.json file). I move this issue for the next release.

**Comment by feserafim** [comment]
Also detected that this modal window won't close if you click on "Close" button. 
Maybe, modal window should implement a close callback by default that calls `hideModal()`.

**Comment by feserafim** [comment]
Default window modal closing has been implemented on #248.
