### ISSUE TITLE
Twitter always asks for authorization

### ISSUE THREAD

**Issue by feserafim** [isa-group/ideas-studio#142]
This issue aims to find out why this is happening now and if there is a possibility to avoid authorization every time you login.

> Here is a **screenshot** (in Spanish):
> ![captura de pantalla 2016-03-15 a las 12 20 29](https://cloud.githubusercontent.com/assets/2706008/13776084/6a0f6628-eaa8-11e5-8747-05aa2cdc7ea4.png)

**Comment by antgamdia** [comment]
![image](https://cloud.githubusercontent.com/assets/11535726/15510892/9e666666-21d9-11e6-9750-163295299fcf.png)

Solved at Twitter configuration
