### ISSUE TITLE
Problems with version of aml dependency in the modules

### ISSUE THREAD

**Issue by iremarmar** [isa-group/ideas-studio#147]
All modules I've tried have problems with the version of aml dependency in pom.xml

**Comment by feserafim** [comment]
Could you be more specific with the problem, please? What error it shows to you?

Thanks!

**Comment by antgamdia** [comment]
By now, the latest AML version is 0.9.4 ([show it in maven central](http://search.maven.org/#artifactdetails%7Ces.us.isa%7Caml%7C0.9.4%7Cjar)). What kind of problems are you having?

**Comment by feserafim** [comment]
We've talked personally with @iremarmar and there are some modules which have some wrong (it refers to a snapshot) and unnecessary aml dependency. Hence, some issues have been created in the corresponding repository.
- [https://github.com/isa-group/ideas-yaml-module/issues/2](https://github.com/isa-group/ideas-yaml-module/issues/2)
- [https://github.com/isa-group/ideas-json-module/issues/4](https://github.com/isa-group/ideas-json-module/issues/4)

For that reason, I'm closing this issue.
