### ISSUE TITLE
Upload a file already uploaded using the context menu above the file previously uploaded

### ISSUE THREAD

**Issue by feserafim** [isa-group/ideas-studio#16]
_From @feserafim on October 20, 2015 13:6_

When you try to upload a file that is previously uploaded, no error nor prompt to overwrite is shown

_Copied from original issue: isa-group/ideas-studio-deprecated#16_

**Comment by antgamdia** [comment]
A) Prevent user from uploading an existent file.
B) Prevent user from uploading non-directory files.
