### ISSUE TITLE
Allow other browers than Chrome

### ISSUE THREAD

**Issue by feserafim** [isa-group/ideas-studio#170]
@tuxayo commented on [Wed May 11 2016](https://github.com/isa-group/governify/issues/8)

Because the later it's done, the harder it might be. And having a webapp trapped on one browser is bad (remember the good old IE6 days).
- What are the Chrome only features being used?
- How do you check that the browser is Chrome/Chromium? On another browser I changed the user agent to match to the one of Chrome (and test if the app would still work) but it was not enough to pass the check.

---

@antgamdia commented on [Wed May 11 2016](https://github.com/isa-group/governify/issues/8#issuecomment-218449046)

We're working on analyzing the specific problems when using another browser. Thank you for your comments.

**Comment by tuxayo** [comment]
Thanks a lot! :-D
