### ISSUE TITLE
Log error when there is no workspace

### ISSUE THREAD

**Issue by feserafim** [isa-group/ideas-studio#177]
Here is a screenshot:

> ![captura de pantalla 2016-05-16 a las 13 43 08](https://cloud.githubusercontent.com/assets/2706008/15288601/3dbb2414-1b6c-11e6-8864-758c8055ee5b.png)

**Comment by antgamdia** [comment]
Rel #127

**Comment by antgamdia** [comment]
See @05ed91e0566d817993162cc66caf63bbdfc5f32e
