### ISSUE TITLE
Copying an opened file into a directory

### ISSUE THREAD

**Issue by feserafim** [isa-group/ideas-studio#18]
_From @feserafim on October 20, 2015 13:17_

If you copy an opened file into a directory, the actual opened file modifications will refer to the one which you have just copied.

_Copied from original issue: isa-group/ideas-studio-deprecated#18_

**Comment by pafmon** [comment]
The opened file in the editor should remain linked to the source file copied.

**Comment by feserafim** [comment]
This issue is related to Dynatree meta information (#173). Closing this issue.
