### ISSUE TITLE
generateDemoWorkspace doesn't overwrite an already existent workspace

### ISSUE THREAD

**Issue by juanludlf** [isa-group/ideas-studio#2]
_From @feserafim on October 16, 2015 14:22_

_Copied from original issue: isa-group/ideas-studio-deprecated#2_

**Comment by pafmon** [comment]
We should add a new parameter to the command ("-f")  to force the overwrite. If this parameter is not present , and demo workspace  already exists, it should give an error message and prevent the overwriting
