### ISSUE TITLE
Operation buttons bad overflow 

### ISSUE THREAD

**Issue by antgamdia** [isa-group/ideas-studio#202]
![image](https://cloud.githubusercontent.com/assets/11535726/15573060/c073f1d0-2344-11e6-9de8-41281e53dce7.png)

**Comment by antgamdia** [comment]
![image](https://cloud.githubusercontent.com/assets/11535726/15573493/b287c35a-2347-11e6-8cad-cb0fa9e1bbb0.png)

**Comment by feserafim** [comment]
Great. Thanks for solving it. However I think we should also provide a much more responsive solution by creating a collapse button titled "..." like in some cases when operation name has more than 75 characters
