### ISSUE TITLE
Project cannot be named like user

### ISSUE THREAD

**Issue by antgamdia** [isa-group/ideas-studio#216]
![image](https://cloud.githubusercontent.com/assets/11535726/16557680/864e16c8-41e1-11e6-85c9-21ebd908e5b9.png)

**Comment by antgamdia** [comment]
Username: sas
The problem happens when a path contains username.

**Comment by feserafim** [comment]
It seems there is something wrong with dynatree management of `node.data.keyPath`

**Comment by feserafim** [comment]
Also, another problem just happened to me when I tried to delete a project named like my user. The application is unable to delete the project and show an empty `fileUri`, as you can see in the image.

![](https://i.gyazo.com/95c40fa0ac89d95083bf6b6bff702c09.png)

**Comment by feserafim** [comment]
This issue only occurs after loading workspace, maybe something is destroy `keyPath` references when workspace file tree is loaded (https://github.com/isa-group/ideas-studio/blob/master/src/main/webapp/js/workspaceManager.js#L334).

**Comment by feserafim** [comment]
[constructFileKeyPath](https://github.com/isa-group/ideas-repo/blob/master/src/main/java/es/us/isa/ideas/repo/impl/fs/FSNodeBuilder.java#L99) in ideas-repo doesn't consider repeated names in `keyPath`.

**Comment by feserafim** [comment]
I've created a issue in ideas-repo to fix this issue.
I will keep this issue open until QA implementation for next release.
