### ISSUE TITLE
Add "visibility" and "group" to language manifests

### ISSUE THREAD

**Issue by antgamdia** [isa-group/ideas-studio#297]
In order to manage the visibility and grouping options for language operations, it seems necessary to include two more properties to the language manifest.
IDEAS/Designer should be aware of these properties and group the operations if a `group` property is passed and distinguish between `primary` and `secondary` visibility levels.

**Comment by feserafim** [comment]
The result of this implementation:
![image](https://user-images.githubusercontent.com/2706008/31377715-456c03d8-ada9-11e7-8a63-1f5b92812bd4.png)
