### ISSUE TITLE
/security/loginFailure page has no format

### ISSUE THREAD

**Issue by juanludlf** [isa-group/ideas-studio#3]
_From @feserafim on October 16, 2015 15:25_

_Copied from original issue: isa-group/ideas-studio-deprecated#3_

**Comment by antgamdia** [comment]
![captura](https://cloud.githubusercontent.com/assets/11535726/15316719/8183ead4-1c1e-11e6-9ad4-6947b57b645f.PNG)
This issue is applicable to this screenshot.
