### ISSUE TITLE
Fix unable to sign up new user

### ISSUE THREAD

**Issue by feserafim** [isa-group/ideas-studio#300]
It seems that server is unable to send any email through SMPT. Maybe, this the containerized infrastructure.

**Comment by antgamdia** [comment]
In the new deployment Docker/nginx ecosystem it is possible that mail functions are being restricted due to bad port mappings. A solution would be moving to a _mail as a service_ platform. I would suggest using Sendgrid.

**Comment by antgamdia** [comment]
Sendgird is free under [these conditions](https://sendgrid.com/free/):  Send up to 40,000 emails for the first 30 days and 100 emails per day free forever

**Comment by feserafim** [comment]
I have been reviewing this approach, and it seems that SendGrid throws an error with
```java
Response response = sg.api(request);
```

Maybe, this error is related to some `pom.xml` dependency used by SendGrid.

**Comment by antgamdia** [comment]
I think you have a problem with redundant dependencies:
```
<dependency>
	<groupId>org.apache.httpcomponents</groupId>
	<artifactId>httpcore</artifactId>
	<version>XXX</version>
</dependency>
<dependency>
	<groupId>org.apache.httpcomponents</groupId>
	<artifactId>httpclient</artifactId>
	<version>XXX</version>
</dependency>
```

I suggest updating all the dependencies related to httpcomponents to the lastest version as recommended in https://github.com/sendgrid/sendgrid-java/pull/162.
