### ISSUE TITLE
Can't connect user account to Facebook, LinkedIn and Github social network

### ISSUE THREAD

**Issue by feserafim** [isa-group/ideas-studio#31]
_From @feserafim on October 20, 2015 21:40_

Trying to connect an user account to any of those social network won't work.

_Copied from original issue: isa-group/ideas-studio-deprecated#31_

**Comment by antgamdia** [comment]
Facebook, LinkedIn and Github support on IDEAS is deprecated. Only Twitter and Google is supported. Closing issue.
