### ISSUE TITLE
Can't connect or login with Google social network in a different application base path

### ISSUE THREAD

**Issue by feserafim** [isa-group/ideas-studio#32]
_From @feserafim on October 20, 2015 21:45_

If you're using a different application base path, anyone distinct to `https://labs.isa.us.es:8181/IDEAS`, Google OAuth won't recognise your path and the connection will fail.

_Copied from original issue: isa-group/ideas-studio-deprecated#32_

**Comment by antgamdia** [comment]
Google does not allow this feature.
