### ISSUE TITLE
Creating a project with a strange character while "Create" button is disabled

### ISSUE THREAD

**Issue by feserafim** [isa-group/ideas-studio#34]
_From @feserafim on October 20, 2015 21:56_

You're able to create any project with a strange character by pressing return key.
The system stops to validates the project name although there is a strange character.

_Copied from original issue: isa-group/ideas-studio-deprecated#34_

**Comment by feserafim** [comment]
Create project using disabled button will be solved in #55

**Comment by antgamdia** [comment]
Duplicated issue. Closing.
