### ISSUE TITLE
When workspace is created with the same name of an existing workspace, it overwrites and deletes all previous content

### ISSUE THREAD

**Issue by pafmon** [isa-group/ideas-studio#51]

**Comment by feserafim** [comment]
It seems workspace won't be overwrite anymore. Although there is still a problem with the modal error generated, issue #162.

![5fe411fa5bed23fdf5c51a03193d98d8](https://cloud.githubusercontent.com/assets/2706008/14911832/466be142-0df8-11e6-86a4-63a7a04a8b52.gif)
