### ISSUE TITLE
Uploading a file into a file

### ISSUE THREAD

**Issue by feserafim** [isa-group/ideas-studio#6]
_From @feserafim on October 19, 2015 10:41_

If you have selected a file on IDEAS file tree and you try to upload a file, the uploaded file will be inside the selected file. The selected file interface will act as a folder.
Also, the uploaded file won't be saved anywhere. You can check that by refreshing the page.

_Copied from original issue: isa-group/ideas-studio-deprecated#6_

**Comment by feserafim** [comment]
_From @gabrielhruiz on October 19, 2015 14:22_

Sorry, I can't work in the said bug, but I think that this is the fix:

File: src/webapp/js/dynatree/projectsTree.js, 
line: 248 & 152, 
event: onDrop.

The function move the dynatree elements but not check that the destiny folder was a real folder. In fact, has to be consistency between dynatree client and workspace manager (server).

**Comment by feserafim** [comment]
Reopening this issue because branch fix doesn't consider name conflict.

**Comment by antgamdia** [comment]
Ref #16. Closed.
