### ISSUE TITLE
"Save changes" button disappears when you change tab

### ISSUE THREAD

**Issue by feserafim** [isa-group/ideas-studio#61]
This happens if the user clicks on "Social" tab first and then clicks on "Login information". 

![captura de pantalla 2015-12-03 a las 16 54 25](https://cloud.githubusercontent.com/assets/2706008/11565524/ad884a7a-99de-11e5-90b3-bb3b32f8fe70.png)

**Comment by antgamdia** [comment]
Rel @c0e05162d68c2efa2382664982290fc2d866592d
