### ISSUE TITLE
Dynatree projects are reordered only by a page refresh

### ISSUE THREAD

**Issue by feserafim** [isa-group/ideas-studio#7]
_From @feserafim on October 19, 2015 12:57_

Dynatree projects are ordered alphabetically. This order is only applied when the user refreshes the page, but not when a new project is created.

_Copied from original issue: isa-group/ideas-studio-deprecated#7_

**Comment by antgamdia** [comment]
Make a custom sorting: first folders lexicographically, then files lexicographically.
