### ISSUE TITLE
[new module] ideas-yaml-module

### ISSUE THREAD

**Issue by malim360** [isa-group/ideas-studio#86]
Name: Manuel Arenillas Luna
Github user: malim360

**Comment by feserafim** [comment]
Your repository has been created with the following url: https://github.com/isa-group/ideas-yaml-module.git

If you had been working previously with git, you can push an the existing repository from the command line

```
git remote add origin https://github.com/isa-group/ideas-yaml-module.git
git push -u origin master
```

Greetings!

**Comment by malim360** [comment]
WAR - YAML Language

https://drive.google.com/file/d/0B14YjuuFOqD7UzFPUEM4R0J1c2M/view?usp=sharing

**Comment by malim360** [comment]
WAR - YAML Language

https://drive.google.com/file/d/0B14YjuuFOqD7OS1xZVd3WGR1Z0U/view?usp=sharing
