### ISSUE TITLE
Error Colour the same language

### ISSUE THREAD

**Issue by malim360** [isa-group/ideas-studio#88]
Ideas colour with different colours the same language. 

Example:

![cc51f9858bdc7fe1cdecad0120c599da](https://cloud.githubusercontent.com/assets/2915744/12390184/0fd8f274-bdde-11e5-911b-f540fc74ee01.gif)

Ideas colours JSON in blue or green, it depends on languages which was selected before.

JSON do not have theme.js.

**Comment by antgamdia** [comment]
Solved issue in module repos. A release of each module is necessary in order to solve this problem.

**Comment by feserafim** [comment]
Issue moved to [isa-group/ideas-module-iagree #13](https://github.com/isa-group/ideas-module-iagree/issues/13) via [**ZenHub.io**](https://www.zenhub.io/)
